services:
  app:
    image: dbouraoui/kernallab:latest
    build: .
    networks:
      - public
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  caddy:
    image: caddy:alpine
    networks:
      - public
      - internal
    volumes:
      - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
      - ./:/app
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=public"
        - "traefik.http.routers.kernallab.rule=Host(`myrocket.fr`)"
        - "traefik.http.routers.kernallab.entrypoints=websecure"
        - "traefik.http.services.kernallab.loadbalancer.server.port=80"
      replicas: 1

networks:
  public:
    external: true
  internal:
    driver: overlay
    attachable: true
