services:
  app:
    image: dbouraoui/kernallab:latest
    environment:
      - APP_KEY=base64:2qpevAdFCtczVothM8wE1zZ1Dyu/gFWgWtnukZShw90=
      - APP_URL=${APP_URL}
      - APP_DEBUG=true
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  caddy:
    image: caddy:alpine
    networks:
      - public
      - internal
    volumes:
      - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
      - ./:/app
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kernellab.rule=Host(`myrocket.fr`) || Host(`www.myrocket.fr`)"
        - "traefik.http.routers.kernellab.entrypoints=websecure"
        - "traefik.http.routers.kernellab.tls.certresolver=myresolver"
        - "traefik.http.services.kernellab.loadbalancer.server.port=80"
      replicas: 1

networks:
  public:
    external: true
  internal:
    driver: overlay
    attachable: true
