services:
  app:
    image: dbouraoui/kernallab:latest
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  caddy:
    image: caddy:alpine
    networks:
      - public
      - internal
    volumes:
      - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
      - ./:/app
    deploy:
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.kernellab.rule=Host(`myrocket.fr`)"
        - "traefik.http.routers.kernellab.entrypoints=websecure"
        - "traefik.http.routers.kernellab.tls.certresolver=myresolver"
        - "traefik.http.routers.kernellab.service=kernellab-svc"
        - "traefik.http.services.kernellab-svc.loadbalancer.server.port=80"
      replicas: 1

networks:
  public:
    external: true
  internal:
    driver: overlay
    attachable: true
