services:
  app:
    image: dbouraoui/kernallab:latest
    networks:
      - internal
      - public
    volumes:
      - /home/ubuntu/mon-app/.env:/var/www/html/.env
      - public_web:/var/www/html/public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M

  caddy:
    image: caddy:alpine
    networks:
      - public
      - internal
    volumes:
      - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
      - public_web:/var/www/html/public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kernellab.rule=Host(`myrocket.fr`) || Host(`www.myrocket.fr`)"
        - "traefik.http.routers.kernellab.entrypoints=websecure"
        - "traefik.http.routers.kernellab.tls.certresolver=myresolver"
        - "traefik.http.services.kernellab.loadbalancer.server.port=80"
      replicas: 1

volumes:
  public_web:

networks:
  public:
    external: true
  internal:
    driver: overlay
    attachable: true
