services:
  app:
    container_name: kernallab
    image: ghcr.io/${GITHUB_NAME}/${REPO_NAME}:latest
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.monapp.rule=Host(`myrocket.fr`)"
        - "traefik.http.routers.monapp.entrypoints=websecure"
        - "traefik.http.routers.monapp.tls.certresolver=myresolver"
        - "traefik.http.services.monapp.loadbalancer.server.port=80"
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback

volumes:
  caddy_data:
  caddy_config:
