services:
  app:
    build: .
    image: kernellab-app:local
    networks:
      - traefik-public
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.monapp.rule=Host(`myrocket.fr`)"
        - "traefik.http.routers.monapp.entrypoints=websecure"
        - "traefik.http.routers.monapp.tls.certresolver=myresolver"
        - "traefik.http.services.monapp.loadbalancer.server.port=80"
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback

volumes:
  caddy_data:
  caddy_config:
networks:
      traefik-public:
        external: true
